<?php

namespace AppBundle\Repository;

use AppBundle\Contracts\Repository\DrmInterface;
use AppBundle\Entity\Drm;
use Doctrine\ORM\EntityRepository;

/**
 * DrmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrmRepository extends EntityRepository implements DrmInterface
{
    /**
     * @param $id
     * @return Drm
     */
    public function findById($id)
    {
        return $this->find($id);
    }
}
