<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KlpcmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KlpcmRepository extends EntityRepository
{
}
