<?php

namespace AppBundle\Repository;

use AppBundle\Contracts\Repository\PeminjamanInterface;
use AppBundle\Entity\Peminjaman;
use Doctrine\ORM\EntityRepository;

/**
 * PeminjamanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeminjamanRepository extends EntityRepository implements PeminjamanInterface
{

    /**
     * @param $id
     * @return Peminjaman
     */
    public function findById($id)
    {
        return $this->find($id);
    }


    /**
     * @param $drm
     * @return Peminjaman
     */
    public function findByDrmId($drm)
    {
        return $this->findOneBy(['drm'=>$drm]);
    }
}
