<?php

namespace AppBundle\Repository;

use AppBundle\Contracts\Repository\UserInterface;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserInterface
{
    /**
     * @param $id
     * @return User
     */
    public function findById($id)
    {
        return $this->find($id);
    }

    /**
     * @param $username
     * @return User
     */
    public function findByUsername($username)
    {
        return $this->findOneBy(['username'=>$username]);
    }

    /**
     * @param $role
     * @return User
     */
    public function findByRole($role)
    {
        return $this->findOneBy(['role'=>$role]);
    }
}
