app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix: /

app_login:
    path: /login
    defaults:
      _controller: AppBundle:Security:login

app_login_check:
    path: /login_check
    defaults:
      _controller: PrinooBundle:Security:loginCheck
