app_admin_index:
    path: /
    defaults:
      _controller: AppBundle:Admin:index

app_admin_daftar_pasien:
    path: /pasien
    defaults:
      _controller: AppBundle:Pasien:getAllPasien

app_admin_input_pasien:
    path: /input-pasien
    defaults:
      _controller: AppBundle:Pasien:inputPasien

app_admin_update_pasien:
    path: /update-pasien/{id}
    defaults:
      _controller: AppBundle:Pasien:updatePasien

app_admin_delete_pasien:
    path: /delete-pasien/{id}
    defaults:
      _controller: AppBundle:Pasien:deletePasien

app_admin_input_drm:
    path: /input-drm
    defaults:
      _controller: AppBundle:Admin:inputDrm

app_admin_daftar_drm:
    path: /drm
    defaults:
      _controller: AppBundle:Admin:getAllDrm

app_admin_input_diagnosa:
    path: /input-diagnosa
    defaults:
      _controller: AppBundle:Diagnosa:inputDiagnosa

app_admin_daftar_diagnosa:
    path: /diagnosa
    defaults:
      _controller: AppBundle:Diagnosa:listDiagnosa

app_admin_update_diagnosa:
    path: /update-diagnosa/{id}
    defaults:
      _controller: AppBundle:Diagnosa:updateDiagnosa

app_admin_delete_diagnosa:
    path: /delete-diagnosa/{id}
    defaults:
      _controller: AppBundle:Diagnosa:deleteDiagnosa

app_admin_input_ruangan:
    path: /input-ruangan
    defaults:
      _controller: AppBundle:Ruangan:inputRuangan

app_admin_daftar_ruangan:
    path: /ruangan
    defaults:
      _controller: AppBundle:Ruangan:listRuangan

app_admin_input_poli:
    path: /input-poli
    defaults:
      _controller: AppBundle:Poli:inputPoli

app_admin_daftar_poli:
    path: /poli
    defaults:
      _controller: AppBundle:Poli:listPoli

app_admin_input_dokter:
    path: /input-dokter
    defaults:
      _controller: AppBundle:Dokter:inputDokter

app_admin_daftar_dokter:
    path: /dokter
    defaults:
      _controller: AppBundle:Dokter:listDokter

app_admin_input_penjamin:
    path: /input-penjamin
    defaults:
      _controller: AppBundle:Penjamin:inputPenjamin

app_admin_daftar_penjamin:
    path: /penjamin
    defaults:
      _controller: AppBundle:Penjamin:daftarPenjamin

app_admin_daftar_filling:
    path: /filling
    defaults:
      _controller: AppBundle:Admin:getAllFilling

app_admin_daftar_peminjaman:
    path: /peminjaman
    defaults:
      _controller: AppBundle:Admin:getAllPeminjaman

app_admin_update_peminjaman:
    path: /update-peminjaman/{id}
    defaults:
      _controller: AppBundle:Admin:updatePeminjaman

app_admin_detail_peminjaman:
    path: /detail-peminjaman/{id}
    defaults:
      _controller: AppBundle:Admin:allDetailPeminjaman

app_admin_update_dokter:
    path: /update-dokter/{id}
    defaults:
      _controller: AppBundle:Dokter:updateDokter

app_admin_delete_dokter:
    path: /delete-dokter/{id}
    defaults:
      _controller: AppBundle:Dokter:deleteDokter

app_admin_update_ruangan:
    path: /update-ruangan/{id}
    defaults:
      _controller: AppBundle:Ruangan:updateRuangan

app_admin_delete_ruangan:
    path: /delete-ruangan/{id}
    defaults:
      _controller: AppBundle:Ruangan:deleteRuangan

app_admin_update_penjamin:
    path: /update-penjamin/{id}
    defaults:
      _controller: AppBundle:Penjamin:updatePenjamin

app_admin_delete_penjamin:
    path: /delete-penjamin/{id}
    defaults:
      _controller: AppBundle:Penjamin:deletePenjamin

app_admin_update_poli:
    path: /update-poli/{id}
    defaults:
      _controller: AppBundle:Poli:updatePoli

app_admin_delete_poli:
    path: /delete-poli/{id}
    defaults:
      _controller: AppBundle:Poli:deletePoli

app_admin_list_klpcm:
    path: /klpcm
    defaults:
      _controller: AppBundle:Admin:getAllKlpcm

app_admin_update_klpcm:
    path: /update-klpcm/{id}
    defaults:
      _controller: AppBundle:Admin:updateKlpcm

app_admin_detail_klpcm:
    path: /detail-klpcm/{id}
    defaults:
      _controller: AppBundle:Admin:getDetailKlpcm