AppBundle\Entity\Diagnosa:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DiagnosaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        namaDiagnosa:
            type: string
            length: 255
            unique: false
            column: nama_diagnosa
    lifecycleCallbacks: {  }
