AppBundle\Entity\Drm:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DrmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
         diagnosa:
                targetEntity: Diagnosa
                joinColumn:
                  name: diagnosa
                  referencedColumnName: id
                  onDelete: "SET NULL"
         pasien:
                targetEntity: Pasien
                joinColumn:
                  name: pasien
                  referencedColumnName: id
                  onDelete: "SET NULL"

         penjamin:
               targetEntity: Penjamin
               joinColumn:
                  name: penjamin
                  referencedColumnName: id
                  onDelete: "SET NULL"

         dokter:
              targetEntity: Dokter
              joinColumn:
                  name: dokter
                  referencedColumnName: id
                  onDelete: "SET NULL"

         ruangan:
              targetEntity: Ruangan
              joinColumn:
                  name: ruangan
                  referencedColumnName: id
                  onDelete: "SET NULL"

    fields:
        tglMrs:
            type: datetime
            column: tgl_mrs
        tglKrs:
            type: datetime
            column: tgl_krs
        tglSetor:
            type: datetime
            column: tgl_setor
        catatanJam:
            type: integer
            column: catatan_jam
        kondisiPulang:
            type: string
            length: 255
            column: kondisi_pulang
        rujukan:
            type: string
            length: 255
            nullable: true
        operasi:
            type: integer
        jenisOperasi:
            type: integer
            column: jenis_operasi
            nullable: true
        jenisBerkas:
            type: integer
            column: jenis_berkas
            nullable: true
        isValidated:
            type: integer
            column: is_validated
            nullable: true
    lifecycleCallbacks: {  }
