AppBundle\Entity\Drm:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DrmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
         diagnosaId:
                targetEntity: Diagnosa
                joinColumn:
                  name: diagnosa_id
                  referencedColumnName: id
                  unique: false
         pasien:
                targetEntity: Pasien
                joinColumn:
                  name: pasien
                  referencedColumnName: id
                  unique: false

         penjamin:
               targetEntity: Penjamin
               joinColumn:
                  name: penjamin
                  referencedColumnName: id
                  unique: false

         dokter:
              targetEntity: Dokter
              joinColumn:
                  name: dokter
                  referencedColumnName: id
                  unique: false
         ruangan:
              targetEntity: Ruangan
              joinColumn:
                  name: ruangan
                  referencedColumnName: id
                  unique: false
    fields:
        tglMrs:
            type: datetime
            column: tgl_mrs
        tglKrs:
            type: datetime
            column: tgl_krs
        tglSetor:
            type: datetime
            column: tgl_setor
        catatanJam:
            type: time
            column: catatan_jam
        kondisiPulang:
            type: string
            length: 255
            column: kondisi_pulang
        operasi:
            type: integer
        jenisOperasi:
            type: integer
            column: jenis_operasi
            nullable: true
        jenisBerkas:
            type: integer
            column: jenis_berkas
        isValidated:
            type: integer
            column: is_validated
            nullable: true
    lifecycleCallbacks: {  }
