AppBundle\Entity\Klpcm:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\KlpcmRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToOne:
        drm:
            targetEntity: Drm
            joinColumn:
                  name: drm
                  referencedColumnName: id
                  onDelete: "SET NULL"

    manyToOne:
        poli:
            targetEntity: Poli
            joinColumn:
                  name: poli
                  referencedColumnName: id
                  onDelete: "SET NULL"
    fields:
        pr:
            type: integer
        tglSetor:
            type: datetime
            column: tgl_setor
            nullable: true
        tglKembali:
            type: datetime
            column: tgl_kembali
        catatanJam:
            type: integer
            column: catatan_jam
    lifecycleCallbacks: {  }
