AppBundle\Entity\Operasi:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\OperasiRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        namaOperasi:
            type: string
            length: 255
            column: nama_operasi
    lifecycleCallbacks: {  }
