AppBundle\Entity\Peminjaman:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\PeminjamanRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
         drm:
            targetEntity: Drm
            joinColumn:
                name: drm
                referencedColumnName: id
                onDelete: "SET NULL"
    fields:
        tglPeminjaman:
            type: datetime
            column: tgl_peminjaman
        namaPeminjam:
            type: string
            length: 255
            column: nama_peminjam
        petugasRekamMedis:
            type: string
            length: 255
            column: petugas_rekam_medis
        tglKembali:
            type: datetime
            column: tgl_kembali
        namaPengembalian:
            type: string
            length: 255
            column: nama_pengembalian
        unitPeminjam:
            type: string
            length: 255
            column: unit_peminjam
        unitPengembalian:
            type: string
            length: 255
            column: unit_pengembalian
    lifecycleCallbacks: {  }
